let x = 1000;
console.log(x.toPrecision(5));
console.log(x.toPrecision(4));
console.log(x.toPrecision(3));
console.log(x.toPrecision(2));
console.log(x.toPrecision(1));
x = 155.335;
console.log(x.toPrecision(6));
console.log(x.toPrecision(5));
console.log(x.toPrecision(4));
console.log(x.toPrecision(3));
console.log(x.toPrecision(2));
console.log(x.toPrecision(1));